baseURL = "https://www.atonidas.com/"
languageCode = "en-us"
title = "aka Atonidas"
theme = "anatole"
enableEmoji = true

[params]
    title = "HỒNG MINH TRIẾT"
    author = "Hồng Minh Triết"
    description = """
    Born on November 2<sup>nd</sup> ,1990 in Saigon, Vietnam

    """
    profilePicture = "images/profile.jpg"
    mainSections = [""]

[[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/hongminhtriet/"

[[params.socialIcons]]
    icon = "fas fa-graduation-cap"
    title = "Google Scholar"
    url = "https://scholar.google.com/citations?user=1wiRNJEAAAAJ&hl=en"

[[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "Instagram"
    url = "https://www.instagram.com/atonidas/"

[[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:minhtriet.hong@gmail.com"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"