baseURL = "http://minhtriethong.github.io/portfolio/"
languageCode = "en-us"
title = "aka Atonidas"
theme = "anatole"

[params]
title = "HỒNG MINH TRIẾT"
author = "Hồng Minh Triết"
description = "Call me /'treat/"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"